<a href="https://colab.research.google.com/github/Lomada-Sahithi/Machine-Learning-Sem-5/blob/main/5_8_Linear_Regression_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

In [ ]:
data = pd.DataFrame({

'Weight':[79,69,73,95,82,55,69,71,64,69],

'Height':[1.80,1.68,1.82,1.70,1.87,1.55,1.50,1.78,1.67,1.64],

'Age':[35,39,25,60,27,18,89,42,16,52],

'Gender':['Male','Male','Male','Male','Male','Female','Female','Female','Female','Female']

})

In [ ]:
data

   Weight  Height  Age  Gender
0      79    1.80   35    Male
1      69    1.68   39    Male
2      73    1.82   25    Male
3      95    1.70   60    Male
4      82    1.87   27    Male
5      55    1.55   18  Female
6      69    1.50   89  Female
7      71    1.78   42  Female
8      64    1.67   16  Female
9      69    1.64   52  Female

In [ ]:
data.head()

   Weight  Height  Age Gender
0      79    1.80   35   Male
1      69    1.68   39   Male
2      73    1.82   25   Male
3      95    1.70   60   Male
4      82    1.87   27   Male

In [ ]:
data.shape

(10, 4)

In [ ]:
data.isnull().sum()

Weight    0
Height    0
Age       0
Gender    0
dtype: int64

In [ ]:
encoder=LabelEncoder()

data['Gender']=encoder.fit_transform(data['Gender'])

In [ ]:
X=data[['Height','Age','Gender']]

y=data['Weight']

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
model= LinearRegression()

In [ ]:
model.fit(X_train,y_train)

LinearRegression()

In [ ]:
y_pred=model.predict(X_test)

In [ ]:
print(y_pred)
print(y_test)

[56.85651025 79.10576115]
8    64
1    69
Name: Weight, dtype: int64

In [ ]:
print("MAE =",mean_absolute_error(y_test,y_pred))

print("MSE =",mean_squared_error(y_test,y_pred))

print("RMSE =",np.sqrt(mean_squared_error(y_test,y_pred)))

print("R2 =",r2_score(y_test,y_pred))

MAE = 8.624625451606978
MSE = 76.57792714844265
RMSE = 8.750881506936468
R2 = -11.252468343750825